// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// recAcf
NumericMatrix recAcf(int lmax, List ProdPairs, NumericVector yCummean, NumericVector yCumsum);
RcppExport SEXP _rcppacf_recAcf(SEXP lmaxSEXP, SEXP ProdPairsSEXP, SEXP yCummeanSEXP, SEXP yCumsumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type lmax(lmaxSEXP);
    Rcpp::traits::input_parameter< List >::type ProdPairs(ProdPairsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type yCummean(yCummeanSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type yCumsum(yCumsumSEXP);
    rcpp_result_gen = Rcpp::wrap(recAcf(lmax, ProdPairs, yCummean, yCumsum));
    return rcpp_result_gen;
END_RCPP
}
// rollAcf
NumericMatrix rollAcf(int lmax, double m, NumericMatrix ProdPairs, NumericVector yRollmean, List yRollsum);
RcppExport SEXP _rcppacf_rollAcf(SEXP lmaxSEXP, SEXP mSEXP, SEXP ProdPairsSEXP, SEXP yRollmeanSEXP, SEXP yRollsumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type lmax(lmaxSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type ProdPairs(ProdPairsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type yRollmean(yRollmeanSEXP);
    Rcpp::traits::input_parameter< List >::type yRollsum(yRollsumSEXP);
    rcpp_result_gen = Rcpp::wrap(rollAcf(lmax, m, ProdPairs, yRollmean, yRollsum));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rcppacf_recAcf", (DL_FUNC) &_rcppacf_recAcf, 4},
    {"_rcppacf_rollAcf", (DL_FUNC) &_rcppacf_rollAcf, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_rcppacf(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
