# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

recAcf <- function(lmax, ProdPairs, yCummean, yCumsum) {
    .Call(`_rcppacf_recAcf`, lmax, ProdPairs, yCummean, yCumsum)
}

rollAcf <- function(lmax, m, ProdPairs, yRollmean, yRollsum) {
    .Call(`_rcppacf_rollAcf`, lmax, m, ProdPairs, yRollmean, yRollsum)
}

